### PR TITLE
window.parent instead of top

### PR DESCRIPTION
**Pull request by ocke**
:v:

/cc @zendesk/vegemite

### Description
.parent instead of .top

### References
* JIRA: 

### Risks
- framwork sdk stops working because it can't connect anymore

### CODE REVIEW

**Comment by sandlerr** [comment]
:+1:

**Comment by svizzari** [comment]
👍

**Comment by danielbreves** [comment]
There some references to `window.top` [here](https://github.com/zendesk/zendesk_app_framework_sdk/blob/master/spec/client_spec.js), it may make sense to update them for consistency.

**Comment by ocke** [comment]
good find. will address

**Pull request merged**
