### PR TITLE
[AF-311] Revert docs that are now live

### PR DESCRIPTION
**Pull request by ocke**
:v:

/cc @zendesk/vegemite

### Description
Revert docs being live

### References
* JIRA: 

### Risks

### CODE REVIEW

**Comment by sandlerr** [comment]
:+1:

**Comment by svizzari** [comment]
Retrospective 👍

**Comment by sandlerr** [comment]
@ocke this needs a followup to put them in a group

**Comment by danielbreves** [comment]
Why not keep them with a double slash instead?

**Comment by sandlerr** [comment]
@ocke is going to revert this revert to make them available to a beta group in hercules. We found this was the only way to make a doc only visible to a group.

**Comment by ocke** [comment]
I've reverted this

**Comment by danielbreves** [comment]
@sandlerr so we got rid of these docs to unpublish them, now we revert the revert to publish them to the beta group?

**Comment by danielbreves** [comment]
For that to work the file needs to be hidden, not just the diff right? That's not clear from the UI.

**Comment by sandlerr** [comment]
yes that's right. @ocke is going to create a new 'v2' file for these docs. Any day now.

**Comment by sandlerr** [comment]
Sorry, just saw that you're working on it

**Pull request merged**
